# homelab-gitops/system/argocd/values.yaml
argo-cd:
  server:
    service:
      type: NodePort
      nodePort: 30080
      annotations: {}
      labels: {}
  namespace: argocd

  configs:
    params:
      server.insecure: true # so you can use http:// without certs
    cm:
      timeout.reconciliation: 30s
