apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: cnpg
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.26.1
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
