apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: cnpg
  source:
    repoURL: https://github.com/andrewknoesen/games_rule_chatbot.git
    targetRevision: main
    path: charts/cluster_infra/postgresql_infra
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
