apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: metallb
  source:
    repoURL: https://github.com/andrewknoesen/network.git
    targetRevision: main
    path: charts/loadbalancer
    helm:
      releaseName: loadbalancer
      valueFiles:
        - values.yaml
  destination:
    namespace: loadbalancer
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
