apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: minio
  source:
    repoURL: https://github.com/andrewknoesen/games_rule_chatbot.git
    targetRevision: main
    path: charts/cluster_infra/minio_infra
    helm:
      releaseName: minio-operator
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
