apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network
  namespace: argocd
spec:
  project: network
  source:
    repoURL: https://github.com/andrewknoesen/network.git
    targetRevision: main
    path: charts/network
    helm:
      releaseName: network
      valueFiles:
        - values.yaml
  destination:
    namespace: network
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
